name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: |
            npm install
            npm install @mui/material @emotion/react @emotion/styled
            npm install @mui/icons-material/NotificationsNone

      - name: Build static file
        run: |
            npm run  build
            npm audit fix --force
            
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./build s3://teamhd
